/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    pages: Page;
    posts: Post;
    categories: Category;
    authors: Author;
    'case-studies': CaseStudy;
    'team-members': TeamMember;
    faqs: Faq;
    roles: Role;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    authors: AuthorsSelect<false> | AuthorsSelect<true>;
    'case-studies': CaseStudiesSelect<false> | CaseStudiesSelect<true>;
    'team-members': TeamMembersSelect<false> | TeamMembersSelect<true>;
    faqs: FaqsSelect<false> | FaqsSelect<true>;
    roles: RolesSelect<false> | RolesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
    header: Header;
    footer: Footer;
    'admin-theme': AdminTheme;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    'admin-theme': AdminThemeSelect<false> | AdminThemeSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  /**
   * Izin bersifat aditif: user memperoleh gabungan izin seluruh perannya.
   */
  roles?: (number | Role)[] | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Peran dan hak aksesnya. Perubahan langsung berlaku setelah cache izin kedaluwarsa.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "roles".
 */
export interface Role {
  id: number;
  name: string;
  /**
   * Pengenal teknis. Jangan diubah bila sudah dipakai kode lain.
   */
  slug: string;
  /**
   * Untuk siapa peran ini, supaya admin lain tidak salah memberi akses.
   */
  description?: string | null;
  /**
   * Peran ini mewarisi SELURUH izin induknya, lalu boleh menambah izin sendiri. Pewarisan berlaku berlapis dan hanya bisa menambah, tidak pernah mencabut.
   */
  parent?: (number | null) | Role;
  /**
   * Mengabaikan seluruh centang di bawah. Hanya untuk administrator sistem.
   */
  isSuperAdmin?: boolean | null;
  canAccessAdmin?: boolean | null;
  collectionPermissions?:
    | {
        collection:
          'users' | 'media' | 'pages' | 'posts' | 'categories' | 'authors' | 'case-studies' | 'team-members' | 'faqs';
        create?: boolean | null;
        read?: boolean | null;
        update?: boolean | null;
        delete?: boolean | null;
        /**
         * Dibutuhkan untuk melihat draft dan riwayat versi.
         */
        readVersions?: boolean | null;
        /**
         * Menentukan nasib field yang TIDAK didaftarkan di tab Field untuk entitas ini.
         */
        fieldPolicy?: ('restrict' | 'allowlist') | null;
        fieldAccess?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  globalPermissions?:
    | {
        global: 'site-settings' | 'header' | 'footer';
        read?: boolean | null;
        update?: boolean | null;
        /**
         * Menentukan nasib field yang TIDAK didaftarkan di tab Field untuk entitas ini.
         */
        fieldPolicy?: ('restrict' | 'allowlist') | null;
        fieldAccess?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Peran bawaan yang dibuat skrip bootstrap dan tidak boleh dihapus.
   */
  isSystem?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  /**
   * Tanpa garis miring di depan. Gunakan `home` untuk halaman utama.
   */
  slug: string;
  /**
   * Tambah dan urutkan bagian halaman di sini.
   */
  layout?:
    | (
        | {
            label?: string | null;
            title?: string | null;
            description?: string | null;
            emailPlaceholder?: string | null;
            submitLabel?: string | null;
            stats?:
              | {
                  value: number;
                  suffix?: string | null;
                  label?: string | null;
                  id?: string | null;
                }[]
              | null;
            showCalculator?: boolean | null;
            calculatorTitle?: string | null;
            resultLabel?: string | null;
            defaultMonthly?: number | null;
            defaultYears?: number | null;
            defaultRate?: number | null;
            action?: {
              label?: string | null;
              href?: string | null;
              variant?:
                | (
                    | 'primary'
                    | 'secondary'
                    | 'solid-black'
                    | 'solid-white'
                    | 'outline-primary'
                    | 'outline-white'
                    | 'outline-dark'
                  )
                | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'hero';
          }
        | {
            label?: string | null;
            title?: string | null;
            description?: string | null;
            actions?:
              | {
                  label: string;
                  href?: string | null;
                  variant?:
                    | (
                        | 'primary'
                        | 'secondary'
                        | 'solid-black'
                        | 'solid-white'
                        | 'outline-primary'
                        | 'outline-white'
                        | 'outline-dark'
                      )
                    | null;
                  id?: string | null;
                }[]
              | null;
            stats?:
              | {
                  value: number;
                  /**
                   * Jumlah angka di belakang koma pada animasi hitung.
                   */
                  decimals?: number | null;
                  suffix?: string | null;
                  label?: string | null;
                  id?: string | null;
                }[]
              | null;
            showMarquee?: boolean | null;
            marqueeItems?:
              | {
                  value: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'heroLight';
          }
        | {
            label?: string | null;
            title?: string | null;
            description?: string | null;
            breadcrumbs?:
              | {
                  label: string;
                  /**
                   * Kosongkan untuk butir terakhir yang bukan tautan.
                   */
                  href?: string | null;
                  id?: string | null;
                }[]
              | null;
            homeLabel?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'pageHero';
          }
        | {
            label?: string | null;
            title?: string | null;
            description?: string | null;
            items?:
              | {
                  title: string;
                  detail?: string | null;
                  id?: string | null;
                }[]
              | null;
            actions?:
              | {
                  label: string;
                  href?: string | null;
                  variant?:
                    | (
                        | 'primary'
                        | 'secondary'
                        | 'solid-black'
                        | 'solid-white'
                        | 'outline-primary'
                        | 'outline-white'
                        | 'outline-dark'
                      )
                    | null;
                  id?: string | null;
                }[]
              | null;
            spacing?: ('lg' | 'md' | 'lg-md' | 'md-lg' | 'none') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'about';
          }
        | {
            label?: string | null;
            title?: string | null;
            description?: string | null;
            items?:
              | {
                  title: string;
                  description?: string | null;
                  id?: string | null;
                }[]
              | null;
            actions?:
              | {
                  label: string;
                  href?: string | null;
                  variant?:
                    | (
                        | 'primary'
                        | 'secondary'
                        | 'solid-black'
                        | 'solid-white'
                        | 'outline-primary'
                        | 'outline-white'
                        | 'outline-dark'
                      )
                    | null;
                  id?: string | null;
                }[]
              | null;
            /**
             * Matikan bila section dipakai sebagai daftar polos.
             */
            showCard?: boolean | null;
            tone?: ('light' | 'dark') | null;
            spacing?: ('lg' | 'md' | 'lg-md' | 'md-lg' | 'none') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'benefits';
          }
        | {
            label?: string | null;
            title?: string | null;
            description?: string | null;
            items?:
              | {
                  title: string;
                  description?: string | null;
                  /**
                   * Warna aksen kartu; hanya token yang ada di design system.
                   */
                  accent?: ('primary' | 'secondary' | 'cool_blue' | 'marine' | 'wine_berry' | 'navy_green') | null;
                  id?: string | null;
                }[]
              | null;
            spacing?: ('lg' | 'md' | 'lg-md' | 'md-lg' | 'none') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'servicesGrid';
          }
        | {
            label?: string | null;
            title?: string | null;
            description?: string | null;
            items?:
              | {
                  number?: string | null;
                  title: string;
                  description?: string | null;
                  id?: string | null;
                }[]
              | null;
            highlight?: string | null;
            highlightDetail?: string | null;
            spacing?: ('lg' | 'md' | 'lg-md' | 'md-lg' | 'none') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'advantages';
          }
        | {
            label?: string | null;
            title?: string | null;
            description?: string | null;
            items?:
              | {
                  /**
                   * Kosongkan untuk penomoran otomatis.
                   */
                  number?: string | null;
                  title: string;
                  detail?: string | null;
                  id?: string | null;
                }[]
              | null;
            tone?: ('light' | 'dark') | null;
            spacing?: ('lg' | 'md' | 'lg-md' | 'md-lg' | 'none') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'stepFlow';
          }
        | {
            label?: string | null;
            title?: string | null;
            description?: string | null;
            items?:
              | {
                  value: string;
                  id?: string | null;
                }[]
              | null;
            actionLabel?: string | null;
            actionHref?: string | null;
            tone?: ('light' | 'dark') | null;
            spacing?: ('lg' | 'md' | 'lg-md' | 'md-lg' | 'none') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'integrations';
          }
        | {
            label?: string | null;
            title?: string | null;
            description?: string | null;
            align?: ('left' | 'center') | null;
            items?:
              | {
                  title: string;
                  description?: string | null;
                  accent?: ('primary' | 'secondary' | 'cool_blue' | 'marine' | 'wine_berry' | 'navy_green') | null;
                  id?: string | null;
                }[]
              | null;
            columns?: ('2' | '3' | '4') | null;
            /**
             * "Kaca" hanya terbaca di atas latar gelap.
             */
            variant?: ('solid' | 'outline' | 'glass') | null;
            spacing?: ('lg' | 'md' | 'lg-md' | 'md-lg' | 'none') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'featureGrid';
          }
        | {
            label?: string | null;
            title?: string | null;
            description?: string | null;
            align?: ('left' | 'center') | null;
            items?:
              | {
                  /**
                   * Teks kecil di atas judul, mis. tahun pada linimasa.
                   */
                  eyebrow?: string | null;
                  title: string;
                  detail?: string | null;
                  id?: string | null;
                }[]
              | null;
            columns?: ('2' | '3' | '4') | null;
            spacing?: ('lg' | 'md' | 'lg-md' | 'md-lg' | 'none') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'cardGrid';
          }
        | {
            label?: string | null;
            title?: string | null;
            description?: string | null;
            items?:
              | {
                  name: string;
                  price?: string | null;
                  note?: string | null;
                  features?:
                    | {
                        value: string;
                        id?: string | null;
                      }[]
                    | null;
                  variant?: ('outline' | 'solid') | null;
                  highlight?: boolean | null;
                  highlightLabel?: string | null;
                  id?: string | null;
                }[]
              | null;
            spacing?: ('lg' | 'md' | 'lg-md' | 'md-lg' | 'none') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'pricingPlans';
          }
        | {
            label?: string | null;
            title?: string | null;
            description?: string | null;
            items?:
              | {
                  value: string;
                  label?: string | null;
                  id?: string | null;
                }[]
              | null;
            spacing?: ('lg' | 'md' | 'lg-md' | 'md-lg' | 'none') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'trustIndicators';
          }
        | {
            label?: string | null;
            title?: string | null;
            description?: string | null;
            items?:
              | {
                  quote: string;
                  name: string;
                  role?: string | null;
                  id?: string | null;
                }[]
              | null;
            spacing?: ('lg' | 'md' | 'lg-md' | 'md-lg' | 'none') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'testimonials';
          }
        | {
            label?: string | null;
            title?: string | null;
            description?: string | null;
            items?:
              | {
                  quote: string;
                  name?: string | null;
                  role?: string | null;
                  id?: string | null;
                }[]
              | null;
            tone?: ('light' | 'dark') | null;
            spacing?: ('lg' | 'md' | 'lg-md' | 'md-lg' | 'none') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'clientReviews';
          }
        | {
            label?: string | null;
            title?: string | null;
            description?: string | null;
            items?:
              | {
                  client?: string | null;
                  title: string;
                  summary?: string | null;
                  slug?: string | null;
                  tags?:
                    | {
                        value: string;
                        id?: string | null;
                      }[]
                    | null;
                  metrics?:
                    | {
                        label: string;
                        value?: string | null;
                        id?: string | null;
                      }[]
                    | null;
                  id?: string | null;
                }[]
              | null;
            /**
             * Kosongkan untuk menampilkan semua.
             */
            limit?: number | null;
            spacing?: ('lg' | 'md' | 'lg-md' | 'md-lg' | 'none') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'caseStudies';
          }
        | {
            label?: string | null;
            title?: string | null;
            description?: string | null;
            items?:
              | {
                  year?: string | null;
                  title: string;
                  issuer?: string | null;
                  detail?: string | null;
                  id?: string | null;
                }[]
              | null;
            spacing?: ('lg' | 'md' | 'lg-md' | 'md-lg' | 'none') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'awards';
          }
        | {
            label?: string | null;
            title?: string | null;
            description?: string | null;
            items?:
              | {
                  name: string;
                  role?: string | null;
                  focus?: string | null;
                  id?: string | null;
                }[]
              | null;
            spacing?: ('lg' | 'md' | 'lg-md' | 'md-lg' | 'none') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'team';
          }
        | {
            label?: string | null;
            title?: string | null;
            description?: string | null;
            items?:
              | {
                  title: string;
                  detail?: string | null;
                  id?: string | null;
                }[]
              | null;
            spacing?: ('lg' | 'md' | 'lg-md' | 'md-lg' | 'none') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'securityProtocols';
          }
        | {
            label?: string | null;
            title?: string | null;
            description?: string | null;
            items?:
              | {
                  name: string;
                  role?: string | null;
                  id?: string | null;
                }[]
              | null;
            spacing?: ('lg' | 'md' | 'lg-md' | 'md-lg' | 'none') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'techStack';
          }
        | {
            label?: string | null;
            title?: string | null;
            description?: string | null;
            items?:
              | {
                  city: string;
                  detail?: string | null;
                  role?: string | null;
                  /**
                   * Posisi penanda di peta, mis. "62%". Kosong memakai posisi bawaan.
                   */
                  mapLeft?: string | null;
                  mapTop?: string | null;
                  id?: string | null;
                }[]
              | null;
            tone?: ('light' | 'dark') | null;
            spacing?: ('lg' | 'md' | 'lg-md' | 'md-lg' | 'none') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'globalInfrastructure';
          }
        | {
            label?: string | null;
            title?: string | null;
            description?: string | null;
            tabsLabel?: string | null;
            showLoan?: boolean | null;
            loanLabel?: string | null;
            showFx?: boolean | null;
            fxLabel?: string | null;
            showComparison?: boolean | null;
            comparisonLabel?: string | null;
            comparisonRows?:
              | {
                  product: string;
                  rate?: string | null;
                  tenor?: string | null;
                  fee?: string | null;
                  payout?: string | null;
                  id?: string | null;
                }[]
              | null;
            /**
             * Tujuan tautan "#" ke section ini. Kosongkan bila tidak dipakai.
             */
            htmlId?: string | null;
            spacing?: ('lg' | 'md' | 'lg-md' | 'md-lg' | 'none') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'calculatorTabs';
          }
        | {
            label?: string | null;
            title?: string | null;
            description?: string | null;
            defaultAmount?: number | null;
            defaultRate?: number | null;
            defaultMonths?: number | null;
            /**
             * Tujuan tautan "#" ke section ini. Kosongkan bila tidak dipakai.
             */
            htmlId?: string | null;
            spacing?: ('lg' | 'md' | 'lg-md' | 'md-lg' | 'none') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'loanCalculator';
          }
        | {
            label?: string | null;
            title?: string | null;
            description?: string | null;
            defaultInitial?: number | null;
            defaultMonthly?: number | null;
            defaultRate?: number | null;
            defaultYears?: number | null;
            /**
             * Tujuan tautan "#" ke section ini. Kosongkan bila tidak dipakai.
             */
            htmlId?: string | null;
            spacing?: ('lg' | 'md' | 'lg-md' | 'md-lg' | 'none') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'savingsCalculator';
          }
        | {
            rates?:
              | {
                  name: string;
                  code: string;
                  rate: number;
                  change?: number | null;
                  id?: string | null;
                }[]
              | null;
            defaultAmount?: string | null;
            defaultFrom?: string | null;
            defaultTo?: string | null;
            resultLabel?: string | null;
            disclaimer?: string | null;
            tone?: ('light' | 'dark') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'fxRates';
          }
        | {
            label?: string | null;
            title?: string | null;
            description?: string | null;
            spacing?: ('lg' | 'md' | 'lg-md' | 'md-lg' | 'none') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'eligibilityForm';
          }
        | {
            label?: string | null;
            title?: string | null;
            description?: string | null;
            /**
             * Tujuan tautan "#" ke section ini. Kosongkan bila tidak dipakai.
             */
            htmlId?: string | null;
            spacing?: ('lg' | 'md' | 'lg-md' | 'md-lg' | 'none') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'loanForm';
          }
        | {
            channelsLabel?: string | null;
            channelsTitle?: string | null;
            /**
             * Kosongkan untuk memakai kontak dari Pengaturan Situs. Baris di sini menimpanya.
             */
            channels?:
              | {
                  label: string;
                  value: string;
                  href?: string | null;
                  id?: string | null;
                }[]
              | null;
            formTitle?: string | null;
            topics?:
              | {
                  label: string;
                  value: string;
                  id?: string | null;
                }[]
              | null;
            submitLabel?: string | null;
            spacing?: ('lg' | 'md' | 'lg-md' | 'md-lg' | 'none') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'contactPanel';
          }
        | {
            label?: string | null;
            title?: string | null;
            description?: string | null;
            /**
             * Ditampilkan apa adanya dengan huruf monospace, termasuk indentasi.
             */
            code: string;
            spacing?: ('lg' | 'md' | 'lg-md' | 'md-lg' | 'none') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'codeSample';
          }
        | {
            label?: string | null;
            title?: string | null;
            description?: string | null;
            videoTitle: string;
            caption?: string | null;
            spacing?: ('lg' | 'md' | 'lg-md' | 'md-lg' | 'none') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'videoFeature';
          }
        | {
            label?: string | null;
            title?: string | null;
            description?: string | null;
            actions?:
              | {
                  label: string;
                  href?: string | null;
                  variant?:
                    | (
                        | 'primary'
                        | 'secondary'
                        | 'solid-black'
                        | 'solid-white'
                        | 'outline-primary'
                        | 'outline-white'
                        | 'outline-dark'
                      )
                    | null;
                  id?: string | null;
                }[]
              | null;
            tone?: ('light' | 'dark') | null;
            spacing?: ('lg' | 'md' | 'lg-md' | 'md-lg' | 'none') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'callToAction';
          }
        | {
            label?: string | null;
            title?: string | null;
            description?: string | null;
            items?:
              | {
                  name: string;
                  rate?: string | null;
                  tenor?: string | null;
                  limit?: string | null;
                  id?: string | null;
                }[]
              | null;
            action?: {
              label?: string | null;
              href?: string | null;
              variant?:
                | (
                    | 'primary'
                    | 'secondary'
                    | 'solid-black'
                    | 'solid-white'
                    | 'outline-primary'
                    | 'outline-white'
                    | 'outline-dark'
                  )
                | null;
            };
            /**
             * Tujuan tautan "#" ke section ini. Kosongkan bila tidak dipakai.
             */
            htmlId?: string | null;
            spacing?: ('lg' | 'md' | 'lg-md' | 'md-lg' | 'none') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'loanCategories';
          }
        | {
            label?: string | null;
            title?: string | null;
            description?: string | null;
            items?:
              | {
                  tier: string;
                  score?: string | null;
                  rate?: string | null;
                  detail?: string | null;
                  id?: string | null;
                }[]
              | null;
            spacing?: ('lg' | 'md' | 'lg-md' | 'md-lg' | 'none') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'creditTiers';
          }
        | {
            label?: string | null;
            title?: string | null;
            description?: string | null;
            items?:
              | {
                  reference: string;
                  date?: string | null;
                  description?: string | null;
                  /**
                   * Negatif untuk pengeluaran.
                   */
                  amount?: number | null;
                  id?: string | null;
                }[]
              | null;
            spacing?: ('lg' | 'md' | 'lg-md' | 'md-lg' | 'none') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'transactionHistory';
          }
        | {
            label?: string | null;
            title?: string | null;
            description?: string | null;
            tabsLabel?: string | null;
            groups?:
              | {
                  label: string;
                  items?:
                    | {
                        value: string;
                        id?: string | null;
                      }[]
                    | null;
                  id?: string | null;
                }[]
              | null;
            spacing?: ('lg' | 'md' | 'lg-md' | 'md-lg' | 'none') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'documents';
          }
        | {
            label?: string | null;
            title?: string | null;
            description?: string | null;
            items?:
              | {
                  title: string;
                  excerpt?: string | null;
                  category?: string | null;
                  categorySlug?: string | null;
                  date?: string | null;
                  readingTime?: string | null;
                  slug?: string | null;
                  id?: string | null;
                }[]
              | null;
            actions?:
              | {
                  label: string;
                  href?: string | null;
                  variant?:
                    | (
                        | 'primary'
                        | 'secondary'
                        | 'solid-black'
                        | 'solid-white'
                        | 'outline-primary'
                        | 'outline-white'
                        | 'outline-dark'
                      )
                    | null;
                  id?: string | null;
                }[]
              | null;
            spacing?: ('lg' | 'md' | 'lg-md' | 'md-lg' | 'none') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'blogPreview';
          }
        | {
            items?:
              | {
                  title: string;
                  excerpt?: string | null;
                  category?: string | null;
                  categorySlug?: string | null;
                  date?: string | null;
                  readingTime?: string | null;
                  slug?: string | null;
                  id?: string | null;
                }[]
              | null;
            /**
             * Ditampilkan bila daftar artikel kosong.
             */
            emptyMessage?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'blogGrid';
          }
        | {
            label?: string | null;
            title?: string | null;
            description?: string | null;
            items?:
              | {
                  question: string;
                  answer: string;
                  id?: string | null;
                }[]
              | null;
            /**
             * Kosongkan untuk menampilkan semuanya.
             */
            limit?: number | null;
            actionLabel?: string | null;
            actionHref?: string | null;
            tone?: ('light' | 'dark') | null;
            spacing?: ('lg' | 'md' | 'lg-md' | 'md-lg' | 'none') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'faq';
          }
        | {
            label?: string | null;
            title?: string | null;
            description?: string | null;
            /**
             * Disunting di sini, bukan di canvas Puck — Puck tidak menerima field rich text.
             */
            content?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            spacing?: ('lg' | 'md' | 'lg-md' | 'md-lg' | 'none') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'prose';
          }
      )[]
    | null;
  seo?: {
    title?: string | null;
    description?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  /**
   * Dipakai di /blog/<slug>.
   */
  slug: string;
  excerpt?: string | null;
  category?: (number | null) | Category;
  author?: (number | null) | Author;
  /**
   * Tanggal yang ditampilkan di kartu artikel.
   */
  publishedAt?: string | null;
  /**
   * Mis. "6 menit". Kata "baca" ditambahkan frontend.
   */
  readingTime?: string | null;
  cover?: (number | null) | Media;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  name: string;
  /**
   * Dipakai di /blog-genre/<slug>.
   */
  slug: string;
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "authors".
 */
export interface Author {
  id: number;
  name: string;
  /**
   * Dipakai di /blog-author/<slug>.
   */
  slug: string;
  role?: string | null;
  bio?: string | null;
  photo?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "case-studies".
 */
export interface CaseStudy {
  id: number;
  title: string;
  /**
   * Dipakai di /case-study/<slug>.
   */
  slug: string;
  client?: string | null;
  industry?: string | null;
  summary?: string | null;
  tags?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  metrics?:
    | {
        label: string;
        value?: string | null;
        id?: string | null;
      }[]
    | null;
  cover?: (number | null) | Media;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team-members".
 */
export interface TeamMember {
  id: number;
  name: string;
  role?: string | null;
  focus?: string | null;
  photo?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs".
 */
export interface Faq {
  id: number;
  question: string;
  answer: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'authors';
        value: number | Author;
      } | null)
    | ({
        relationTo: 'case-studies';
        value: number | CaseStudy;
      } | null)
    | ({
        relationTo: 'team-members';
        value: number | TeamMember;
      } | null)
    | ({
        relationTo: 'faqs';
        value: number | Faq;
      } | null)
    | ({
        relationTo: 'roles';
        value: number | Role;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  roles?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  layout?:
    | T
    | {
        hero?:
          | T
          | {
              label?: T;
              title?: T;
              description?: T;
              emailPlaceholder?: T;
              submitLabel?: T;
              stats?:
                | T
                | {
                    value?: T;
                    suffix?: T;
                    label?: T;
                    id?: T;
                  };
              showCalculator?: T;
              calculatorTitle?: T;
              resultLabel?: T;
              defaultMonthly?: T;
              defaultYears?: T;
              defaultRate?: T;
              action?:
                | T
                | {
                    label?: T;
                    href?: T;
                    variant?: T;
                  };
              id?: T;
              blockName?: T;
            };
        heroLight?:
          | T
          | {
              label?: T;
              title?: T;
              description?: T;
              actions?:
                | T
                | {
                    label?: T;
                    href?: T;
                    variant?: T;
                    id?: T;
                  };
              stats?:
                | T
                | {
                    value?: T;
                    decimals?: T;
                    suffix?: T;
                    label?: T;
                    id?: T;
                  };
              showMarquee?: T;
              marqueeItems?:
                | T
                | {
                    value?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        pageHero?:
          | T
          | {
              label?: T;
              title?: T;
              description?: T;
              breadcrumbs?:
                | T
                | {
                    label?: T;
                    href?: T;
                    id?: T;
                  };
              homeLabel?: T;
              id?: T;
              blockName?: T;
            };
        about?:
          | T
          | {
              label?: T;
              title?: T;
              description?: T;
              items?:
                | T
                | {
                    title?: T;
                    detail?: T;
                    id?: T;
                  };
              actions?:
                | T
                | {
                    label?: T;
                    href?: T;
                    variant?: T;
                    id?: T;
                  };
              spacing?: T;
              id?: T;
              blockName?: T;
            };
        benefits?:
          | T
          | {
              label?: T;
              title?: T;
              description?: T;
              items?:
                | T
                | {
                    title?: T;
                    description?: T;
                    id?: T;
                  };
              actions?:
                | T
                | {
                    label?: T;
                    href?: T;
                    variant?: T;
                    id?: T;
                  };
              showCard?: T;
              tone?: T;
              spacing?: T;
              id?: T;
              blockName?: T;
            };
        servicesGrid?:
          | T
          | {
              label?: T;
              title?: T;
              description?: T;
              items?:
                | T
                | {
                    title?: T;
                    description?: T;
                    accent?: T;
                    id?: T;
                  };
              spacing?: T;
              id?: T;
              blockName?: T;
            };
        advantages?:
          | T
          | {
              label?: T;
              title?: T;
              description?: T;
              items?:
                | T
                | {
                    number?: T;
                    title?: T;
                    description?: T;
                    id?: T;
                  };
              highlight?: T;
              highlightDetail?: T;
              spacing?: T;
              id?: T;
              blockName?: T;
            };
        stepFlow?:
          | T
          | {
              label?: T;
              title?: T;
              description?: T;
              items?:
                | T
                | {
                    number?: T;
                    title?: T;
                    detail?: T;
                    id?: T;
                  };
              tone?: T;
              spacing?: T;
              id?: T;
              blockName?: T;
            };
        integrations?:
          | T
          | {
              label?: T;
              title?: T;
              description?: T;
              items?:
                | T
                | {
                    value?: T;
                    id?: T;
                  };
              actionLabel?: T;
              actionHref?: T;
              tone?: T;
              spacing?: T;
              id?: T;
              blockName?: T;
            };
        featureGrid?:
          | T
          | {
              label?: T;
              title?: T;
              description?: T;
              align?: T;
              items?:
                | T
                | {
                    title?: T;
                    description?: T;
                    accent?: T;
                    id?: T;
                  };
              columns?: T;
              variant?: T;
              spacing?: T;
              id?: T;
              blockName?: T;
            };
        cardGrid?:
          | T
          | {
              label?: T;
              title?: T;
              description?: T;
              align?: T;
              items?:
                | T
                | {
                    eyebrow?: T;
                    title?: T;
                    detail?: T;
                    id?: T;
                  };
              columns?: T;
              spacing?: T;
              id?: T;
              blockName?: T;
            };
        pricingPlans?:
          | T
          | {
              label?: T;
              title?: T;
              description?: T;
              items?:
                | T
                | {
                    name?: T;
                    price?: T;
                    note?: T;
                    features?:
                      | T
                      | {
                          value?: T;
                          id?: T;
                        };
                    variant?: T;
                    highlight?: T;
                    highlightLabel?: T;
                    id?: T;
                  };
              spacing?: T;
              id?: T;
              blockName?: T;
            };
        trustIndicators?:
          | T
          | {
              label?: T;
              title?: T;
              description?: T;
              items?:
                | T
                | {
                    value?: T;
                    label?: T;
                    id?: T;
                  };
              spacing?: T;
              id?: T;
              blockName?: T;
            };
        testimonials?:
          | T
          | {
              label?: T;
              title?: T;
              description?: T;
              items?:
                | T
                | {
                    quote?: T;
                    name?: T;
                    role?: T;
                    id?: T;
                  };
              spacing?: T;
              id?: T;
              blockName?: T;
            };
        clientReviews?:
          | T
          | {
              label?: T;
              title?: T;
              description?: T;
              items?:
                | T
                | {
                    quote?: T;
                    name?: T;
                    role?: T;
                    id?: T;
                  };
              tone?: T;
              spacing?: T;
              id?: T;
              blockName?: T;
            };
        caseStudies?:
          | T
          | {
              label?: T;
              title?: T;
              description?: T;
              items?:
                | T
                | {
                    client?: T;
                    title?: T;
                    summary?: T;
                    slug?: T;
                    tags?:
                      | T
                      | {
                          value?: T;
                          id?: T;
                        };
                    metrics?:
                      | T
                      | {
                          label?: T;
                          value?: T;
                          id?: T;
                        };
                    id?: T;
                  };
              limit?: T;
              spacing?: T;
              id?: T;
              blockName?: T;
            };
        awards?:
          | T
          | {
              label?: T;
              title?: T;
              description?: T;
              items?:
                | T
                | {
                    year?: T;
                    title?: T;
                    issuer?: T;
                    detail?: T;
                    id?: T;
                  };
              spacing?: T;
              id?: T;
              blockName?: T;
            };
        team?:
          | T
          | {
              label?: T;
              title?: T;
              description?: T;
              items?:
                | T
                | {
                    name?: T;
                    role?: T;
                    focus?: T;
                    id?: T;
                  };
              spacing?: T;
              id?: T;
              blockName?: T;
            };
        securityProtocols?:
          | T
          | {
              label?: T;
              title?: T;
              description?: T;
              items?:
                | T
                | {
                    title?: T;
                    detail?: T;
                    id?: T;
                  };
              spacing?: T;
              id?: T;
              blockName?: T;
            };
        techStack?:
          | T
          | {
              label?: T;
              title?: T;
              description?: T;
              items?:
                | T
                | {
                    name?: T;
                    role?: T;
                    id?: T;
                  };
              spacing?: T;
              id?: T;
              blockName?: T;
            };
        globalInfrastructure?:
          | T
          | {
              label?: T;
              title?: T;
              description?: T;
              items?:
                | T
                | {
                    city?: T;
                    detail?: T;
                    role?: T;
                    mapLeft?: T;
                    mapTop?: T;
                    id?: T;
                  };
              tone?: T;
              spacing?: T;
              id?: T;
              blockName?: T;
            };
        calculatorTabs?:
          | T
          | {
              label?: T;
              title?: T;
              description?: T;
              tabsLabel?: T;
              showLoan?: T;
              loanLabel?: T;
              showFx?: T;
              fxLabel?: T;
              showComparison?: T;
              comparisonLabel?: T;
              comparisonRows?:
                | T
                | {
                    product?: T;
                    rate?: T;
                    tenor?: T;
                    fee?: T;
                    payout?: T;
                    id?: T;
                  };
              htmlId?: T;
              spacing?: T;
              id?: T;
              blockName?: T;
            };
        loanCalculator?:
          | T
          | {
              label?: T;
              title?: T;
              description?: T;
              defaultAmount?: T;
              defaultRate?: T;
              defaultMonths?: T;
              htmlId?: T;
              spacing?: T;
              id?: T;
              blockName?: T;
            };
        savingsCalculator?:
          | T
          | {
              label?: T;
              title?: T;
              description?: T;
              defaultInitial?: T;
              defaultMonthly?: T;
              defaultRate?: T;
              defaultYears?: T;
              htmlId?: T;
              spacing?: T;
              id?: T;
              blockName?: T;
            };
        fxRates?:
          | T
          | {
              rates?:
                | T
                | {
                    name?: T;
                    code?: T;
                    rate?: T;
                    change?: T;
                    id?: T;
                  };
              defaultAmount?: T;
              defaultFrom?: T;
              defaultTo?: T;
              resultLabel?: T;
              disclaimer?: T;
              tone?: T;
              id?: T;
              blockName?: T;
            };
        eligibilityForm?:
          | T
          | {
              label?: T;
              title?: T;
              description?: T;
              spacing?: T;
              id?: T;
              blockName?: T;
            };
        loanForm?:
          | T
          | {
              label?: T;
              title?: T;
              description?: T;
              htmlId?: T;
              spacing?: T;
              id?: T;
              blockName?: T;
            };
        contactPanel?:
          | T
          | {
              channelsLabel?: T;
              channelsTitle?: T;
              channels?:
                | T
                | {
                    label?: T;
                    value?: T;
                    href?: T;
                    id?: T;
                  };
              formTitle?: T;
              topics?:
                | T
                | {
                    label?: T;
                    value?: T;
                    id?: T;
                  };
              submitLabel?: T;
              spacing?: T;
              id?: T;
              blockName?: T;
            };
        codeSample?:
          | T
          | {
              label?: T;
              title?: T;
              description?: T;
              code?: T;
              spacing?: T;
              id?: T;
              blockName?: T;
            };
        videoFeature?:
          | T
          | {
              label?: T;
              title?: T;
              description?: T;
              videoTitle?: T;
              caption?: T;
              spacing?: T;
              id?: T;
              blockName?: T;
            };
        callToAction?:
          | T
          | {
              label?: T;
              title?: T;
              description?: T;
              actions?:
                | T
                | {
                    label?: T;
                    href?: T;
                    variant?: T;
                    id?: T;
                  };
              tone?: T;
              spacing?: T;
              id?: T;
              blockName?: T;
            };
        loanCategories?:
          | T
          | {
              label?: T;
              title?: T;
              description?: T;
              items?:
                | T
                | {
                    name?: T;
                    rate?: T;
                    tenor?: T;
                    limit?: T;
                    id?: T;
                  };
              action?:
                | T
                | {
                    label?: T;
                    href?: T;
                    variant?: T;
                  };
              htmlId?: T;
              spacing?: T;
              id?: T;
              blockName?: T;
            };
        creditTiers?:
          | T
          | {
              label?: T;
              title?: T;
              description?: T;
              items?:
                | T
                | {
                    tier?: T;
                    score?: T;
                    rate?: T;
                    detail?: T;
                    id?: T;
                  };
              spacing?: T;
              id?: T;
              blockName?: T;
            };
        transactionHistory?:
          | T
          | {
              label?: T;
              title?: T;
              description?: T;
              items?:
                | T
                | {
                    reference?: T;
                    date?: T;
                    description?: T;
                    amount?: T;
                    id?: T;
                  };
              spacing?: T;
              id?: T;
              blockName?: T;
            };
        documents?:
          | T
          | {
              label?: T;
              title?: T;
              description?: T;
              tabsLabel?: T;
              groups?:
                | T
                | {
                    label?: T;
                    items?:
                      | T
                      | {
                          value?: T;
                          id?: T;
                        };
                    id?: T;
                  };
              spacing?: T;
              id?: T;
              blockName?: T;
            };
        blogPreview?:
          | T
          | {
              label?: T;
              title?: T;
              description?: T;
              items?:
                | T
                | {
                    title?: T;
                    excerpt?: T;
                    category?: T;
                    categorySlug?: T;
                    date?: T;
                    readingTime?: T;
                    slug?: T;
                    id?: T;
                  };
              actions?:
                | T
                | {
                    label?: T;
                    href?: T;
                    variant?: T;
                    id?: T;
                  };
              spacing?: T;
              id?: T;
              blockName?: T;
            };
        blogGrid?:
          | T
          | {
              items?:
                | T
                | {
                    title?: T;
                    excerpt?: T;
                    category?: T;
                    categorySlug?: T;
                    date?: T;
                    readingTime?: T;
                    slug?: T;
                    id?: T;
                  };
              emptyMessage?: T;
              id?: T;
              blockName?: T;
            };
        faq?:
          | T
          | {
              label?: T;
              title?: T;
              description?: T;
              items?:
                | T
                | {
                    question?: T;
                    answer?: T;
                    id?: T;
                  };
              limit?: T;
              actionLabel?: T;
              actionHref?: T;
              tone?: T;
              spacing?: T;
              id?: T;
              blockName?: T;
            };
        prose?:
          | T
          | {
              label?: T;
              title?: T;
              description?: T;
              content?: T;
              spacing?: T;
              id?: T;
              blockName?: T;
            };
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  category?: T;
  author?: T;
  publishedAt?: T;
  readingTime?: T;
  cover?: T;
  body?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "authors_select".
 */
export interface AuthorsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  role?: T;
  bio?: T;
  photo?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "case-studies_select".
 */
export interface CaseStudiesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  client?: T;
  industry?: T;
  summary?: T;
  tags?:
    | T
    | {
        value?: T;
        id?: T;
      };
  metrics?:
    | T
    | {
        label?: T;
        value?: T;
        id?: T;
      };
  cover?: T;
  body?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team-members_select".
 */
export interface TeamMembersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  focus?: T;
  photo?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs_select".
 */
export interface FaqsSelect<T extends boolean = true> {
  question?: T;
  answer?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "roles_select".
 */
export interface RolesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  parent?: T;
  isSuperAdmin?: T;
  canAccessAdmin?: T;
  collectionPermissions?:
    | T
    | {
        collection?: T;
        create?: T;
        read?: T;
        update?: T;
        delete?: T;
        readVersions?: T;
        fieldPolicy?: T;
        fieldAccess?: T;
        id?: T;
      };
  globalPermissions?:
    | T
    | {
        global?: T;
        read?: T;
        update?: T;
        fieldPolicy?: T;
        fieldAccess?: T;
        id?: T;
      };
  isSystem?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  name: string;
  tagline?: string | null;
  logo?: (number | null) | Media;
  contact?: {
    email?: string | null;
    phone?: string | null;
    address?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: number;
  mainNav?:
    | {
        label: string;
        /**
         * Kosongkan bila butir ini hanya pembuka dropdown.
         */
        href?: string | null;
        children?:
          | {
              label: string;
              href: string;
              description?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  megaMenu?:
    | {
        label: string;
        items?:
          | {
              label: string;
              href: string;
              description?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  action?: {
    label?: string | null;
    href?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  columns?:
    | {
        title: string;
        links?:
          | {
              label: string;
              href: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Muncul di bawah kolom tautan. Tahun diisi frontend.
   */
  note?: string | null;
  socials?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Tampilan panel admin. Perubahan langsung terlihat setelah disimpan — tanpa restart. Isi tab "Warna & Bentuk" sama dengan panel palet di header; keduanya menyunting data ini.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "admin-theme".
 */
export interface AdminTheme {
  id: number;
  /**
   * Tampil di samping logo pada sidebar dan di judul tab.
   */
  siteTitle?: string | null;
  /**
   * Matikan bila logo Anda sudah memuat nama situs.
   */
  showTitleInNav?: boolean | null;
  /**
   * Tampil di sidebar dan di atas form login.
   */
  logo?: (number | null) | Media;
  /**
   * Opsional. Bila kosong, logo utama dipakai untuk kedua mode.
   */
  logoDark?: (number | null) | Media;
  /**
   * Tinggi render logo dalam piksel.
   */
  logoHeight?: number | null;
  /**
   * Mark kecil untuk favicon dan halaman home. Dipakai juga bila logo kosong.
   */
  icon?: (number | null) | Media;
  /**
   * Opsional. Bila kosong, ikon utama dipakai untuk kedua mode.
   */
  iconDark?: (number | null) | Media;
  /**
   * Titik awal siap pakai. Nilai yang Anda isi sendiri di bawah tetap menang.
   */
  preset?: ('custom' | 'zinc' | 'ocean' | 'forest' | 'sunset' | 'berry' | 'swiss') | null;
  /**
   * Hex, mis. #2563eb. Kosongkan untuk memakai warna dari preset.
   */
  accent?: string | null;
  /**
   * Berlaku untuk seluruh panel: tombol, input, kartu, tabel, dan popover.
   */
  radius?: ('none' | 'sm' | 'md' | 'lg' | 'full') | null;
  /**
   * Inter dan Geist diunduh dari Google Fonts saat panel dibuka; Helvetica dan System memakai font yang sudah ada di perangkat.
   */
  font?: ('default' | 'inter' | 'geist' | 'helvetica' | 'system') | null;
  /**
   * Terpusat membatasi kartu konten pada ~1280px; Penuh membiarkannya memenuhi lebar layar.
   */
  layout?: ('centered' | 'full') | null;
  /**
   * Tambahkan baris untuk entitas yang ingin diatur. Entitas tanpa baris memakai ikon dan grup bawaannya.
   */
  navItems?:
    | {
        /**
         * Collection atau global yang diatur.
         */
        entity:
          | 'collection:users'
          | 'collection:media'
          | 'collection:pages'
          | 'collection:posts'
          | 'collection:categories'
          | 'collection:authors'
          | 'collection:case-studies'
          | 'collection:team-members'
          | 'collection:faqs'
          | 'collection:roles'
          | 'global:site-settings'
          | 'global:header'
          | 'global:footer';
        /**
         * Ikon lucide untuk sidebar, dashboard, dan command palette.
         */
        icon?: string | null;
        /**
         * Judul grup di sidebar. Kosongkan untuk memakai bawaan.
         */
        group?: string | null;
        /**
         * Sembunyikan dari sidebar dan dashboard.
         */
        hidden?: boolean | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Mengisi dua per tiga kiri halaman login. Gunakan gambar lanskap beresolusi tinggi.
   */
  loginBackground?: (number | null) | Media;
  /**
   * Nol berarti gambar tampil apa adanya. Naikkan hanya bila judul dan kalimat pada panel — keduanya putih — tenggelam di atas gambar terang.
   */
  loginOverlay?: number | null;
  loginHeading?: string | null;
  loginTagline?: string | null;
  /**
   * Override token mentah, mis. --pt-radius-card = 10px. Awalan -- boleh dilewat.
   */
  cssVariables?:
    | {
        name: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  /**
   * CSS mentah yang disuntikkan ke panel admin. Tanpa cascade layer, sehingga menang atas aturan tema.
   */
  customCSS?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  name?: T;
  tagline?: T;
  logo?: T;
  contact?:
    | T
    | {
        email?: T;
        phone?: T;
        address?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  mainNav?:
    | T
    | {
        label?: T;
        href?: T;
        children?:
          | T
          | {
              label?: T;
              href?: T;
              description?: T;
              id?: T;
            };
        id?: T;
      };
  megaMenu?:
    | T
    | {
        label?: T;
        items?:
          | T
          | {
              label?: T;
              href?: T;
              description?: T;
              id?: T;
            };
        id?: T;
      };
  action?:
    | T
    | {
        label?: T;
        href?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  columns?:
    | T
    | {
        title?: T;
        links?:
          | T
          | {
              label?: T;
              href?: T;
              id?: T;
            };
        id?: T;
      };
  note?: T;
  socials?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "admin-theme_select".
 */
export interface AdminThemeSelect<T extends boolean = true> {
  siteTitle?: T;
  showTitleInNav?: T;
  logo?: T;
  logoDark?: T;
  logoHeight?: T;
  icon?: T;
  iconDark?: T;
  preset?: T;
  accent?: T;
  radius?: T;
  font?: T;
  layout?: T;
  navItems?:
    | T
    | {
        entity?: T;
        icon?: T;
        group?: T;
        hidden?: T;
        id?: T;
      };
  loginBackground?: T;
  loginOverlay?: T;
  loginHeading?: T;
  loginTagline?: T;
  cssVariables?:
    | T
    | {
        name?: T;
        value?: T;
        id?: T;
      };
  customCSS?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}